use __aligned_u64
this is the fix Dggrr on xda found for the following error he (and now I) experienced when building LineageOS 14.1.

```In file included from external/ebtables/extensions/ebt_pkttype.c:15:
out/target/product/grouper/obj/KERNEL_OBJ/usr/include/linux/if_packet.h:176:2: error: unknown type name 'aligned_u64'
        aligned_u64     seq_num;```

This fixed the build for him, and mine's running fine so far, but I have no idea if this is an error any AOSP builders are facing, and thus whether it should be included here.